#!/bin/bash
# install.sh — reproducible install of wsd-scan
#
# Default: system-wide install (sudo for systemd parts, unit in /etc/systemd/system/).
# --user:  user-level install (unit in ~/.config/systemd/user/, no sudo).
#
# Fills the wsd-scan.service template with runtime values, creates a project
# venv, pip-installs the package, enables + starts the service, and writes
# .install-record (read by uninstall.sh to undo exactly this install).
#
# No ~/.local/bin wrapper is created — set that up manually if wanted.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$REPO_DIR/.venv"
RECORD="$REPO_DIR/.install-record"
TEMPLATE="$REPO_DIR/wsd-scan.service"
SERVICE="wsd-scan"
PACKAGE="wsd-scan"

# Defaults
MODE="system"
TARGET="http://192.168.0.149:8018/wsd"
SELF_IP=""
PORT=6666
SCAN_DIR=""

usage() {
    cat <<EOF
Usage: install.sh [OPTIONS]

Options:
  --user          User-level install (default: system-wide)
  -t, --target    Scanner WSD endpoint URL (default: $TARGET)
  -s, --self      Local IP the scanner can reach
  -p, --port      HTTP listener port (default: $PORT)
  --scan-dir      Scan output directory (default: ~/Pictures/scans)
  -h, --help      Show this help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --user)       MODE="user"; shift ;;
        -t|--target)  TARGET="$2"; shift 2 ;;
        -s|--self)    SELF_IP="$2"; shift 2 ;;
        -p|--port)    PORT="$2"; shift 2 ;;
        --scan-dir)   SCAN_DIR="$2"; shift 2 ;;
        -h|--help)    usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    esac
done

# Prompt for self IP if not provided
if [[ -z "$SELF_IP" ]]; then
    read -rp "Local IP the scanner can reach [192.168.0.110]: " SELF_IP
    SELF_IP="${SELF_IP:-192.168.0.110}"
fi

# Mode-specific paths
if [[ "$MODE" == "system" ]]; then
    UNIT_DST="/etc/systemd/system/$SERVICE.service"
    SERVICE_USER="$USER"
    WANTED_BY="multi-user.target"
else
    UNIT_DST="$HOME/.config/systemd/user/$SERVICE.service"
    SERVICE_USER=""
    WANTED_BY="default.target"
fi

[[ -z "$SCAN_DIR" ]] && SCAN_DIR="$HOME/Pictures/scans"
EXEC="$VENV_DIR/bin/$SERVICE"

echo "=== wsd-scan installer ($MODE mode) ==="
echo "Repo:     $REPO_DIR"
echo "Venv:     $VENV_DIR"
echo "Target:   $TARGET"
echo "Self IP:  $SELF_IP"
echo "Port:     $PORT"
echo "Scan dir: $SCAN_DIR"
echo "Unit:     $UNIT_DST"
[[ -n "$SERVICE_USER" ]] && echo "Run as:   $SERVICE_USER"
echo

# 1. venv + editable install
if [[ ! -d "$VENV_DIR" ]]; then
    echo "[1/3] Creating project venv..."
    python3 -m venv "$VENV_DIR"
else
    echo "[1/3] Project venv exists."
fi
echo "[2/3] Installing package (editable) into venv..."
"$VENV_DIR/bin/pip" install -e "$REPO_DIR" -q

# 2. Fill template and install unit
echo "[3/3] Installing systemd unit..."

# Lines prefixed with #@SYSTEM are system-mode only.
# System mode: strip the prefix (keep the directive).
# User mode:   delete the line entirely.
if [[ "$MODE" == "system" ]]; then
    SYS_FILTER='s|^#@SYSTEM ||'
else
    SYS_FILTER='/^#@SYSTEM/d'
fi

TMPUNIT="$(mktemp)"
sed \
    -e "s|__EXEC__|$EXEC|g" \
    -e "s|__TARGET__|$TARGET|g" \
    -e "s|__SELF_IP__|$SELF_IP|g" \
    -e "s|__PORT__|$PORT|g" \
    -e "s|__SCAN_DIR__|$SCAN_DIR|g" \
    -e "s|__USER__|$SERVICE_USER|g" \
    -e "s|__WANTED_BY__|$WANTED_BY|g" \
    -e "$SYS_FILTER" \
    "$TEMPLATE" > "$TMPUNIT"

mkdir -p "$(dirname "$UNIT_DST")"
if [[ "$MODE" == "system" ]]; then
    sudo cp "$TMPUNIT" "$UNIT_DST"
    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE"
    if systemctl is-active --quiet "$SERVICE"; then
        echo "      Service running — restarting."
        sudo systemctl restart "$SERVICE"
    else
        sudo systemctl start "$SERVICE"
    fi
else
    cp "$TMPUNIT" "$UNIT_DST"
    systemctl --user daemon-reload
    systemctl --user enable "$SERVICE"
    if systemctl --user is-active --quiet "$SERVICE"; then
        echo "      Service running — restarting."
        systemctl --user restart "$SERVICE"
    else
        systemctl --user start "$SERVICE"
    fi
    # Survive logout
    loginctl enable-linger "$USER" 2>/dev/null || true
fi
rm -f "$TMPUNIT"

# Ensure scan dir exists (ReadWritePaths target)
mkdir -p "$SCAN_DIR"

# 3. Write install record for uninstall.sh
cat > "$RECORD" <<EOF
# wsd-scan install record — generated by install.sh, used by uninstall.sh
# Do not edit manually. Delete to make uninstall.sh refuse to run.
INSTALL_MODE=$MODE
SERVICE_NAME=$SERVICE
PACKAGE_NAME=$PACKAGE
UNIT_PATH=$UNIT_DST
VENV_PATH=$VENV_DIR
REPO_DIR=$REPO_DIR
SCAN_DIR=$SCAN_DIR
SERVICE_USER=$SERVICE_USER
TARGET=$TARGET
SELF_IP=$SELF_IP
PORT=$PORT
EOF

echo
echo "=== Install complete ==="
if [[ "$MODE" == "system" ]]; then
    echo "Service:  $(systemctl is-enabled "$SERVICE") / $(systemctl is-active "$SERVICE")"
    echo "Logs:     journalctl -u $SERVICE -f"
else
    echo "Service:  $(systemctl --user is-enabled "$SERVICE") / $(systemctl --user is-active "$SERVICE")"
    echo "Logs:     journalctl --user -u $SERVICE -f"
fi
echo "Exec:     $EXEC"
echo "Record:   $RECORD"
echo
echo "To uninstall:  ./uninstall.sh"
